name: Bug Report
description: Report a bug or issue with the project.
type: Bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is and any supplemental information about the environemnt(s) in which its occurring.
      value: |
          - Browser

          - Org Type

          - Package Version

          - User Info 

          - Screenshots or Videos
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a list of steps to reproduce the bug.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots-or-videos
    attributes:
      label: Screenshots or Videos
      description: Add any screenshots or videos that may help explain the issue.
      placeholder: |
        ex: loom video link, screenshots, etc.