name: Bug Report
description: Report a bug or issue with the project.
title: "[Bug]: "
type: Bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug.
      placeholder: |
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: browsers
    attributes:
      label: Browser
      description: The browser(s) where the bug was observed.
      placeholder: |
        Chrome, Firefox, Safari, Edge, IE11
  - type: textarea
    id: org-type
    attributes:
      label: Org Type
      description: The type of Salesforce Org where the bug was observed.
      placeholder: |
        ex: Summer '25 scratch org
  - type: textarea
    id: package-info
    attributes:
      label: Package Information
      description: The package version where the bug was observed.
      placeholder: |
        ex: 0.13
  - type: textarea
    id: user-type
    attributes:
      label: User Type
      description: The user type(s) that the bug was observed for.
      placeholder: |
        ex: System Admin, Standard User, Guest User
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a list of steps to reproduce the bug.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      descrition: Describe what you expected to happen.
      placeholder: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: |
        A clear and concise description of what currently happens.
    validations:
      required: true
  - type: textarea
    id: screenshots-or-videos
    attributes:
      label: Screenshots or Videos
      description: Add any screenshots or videos that may help explain the issue.
      placeholder: |
        ex: loom video link, screenshots, etc.