name: Feature Template
description: Create a new feature for this project.
type: Feature
body:
  - type: input
    id: persona
    attributes:
      label: Persona
      description: The persona for whom the feature is being created.
      placeholder: |
        ex: Admin, Developer, User
    validations:
      required: true
  - type: input
    id: use-case
    attributes:
      label: Use Case
      description: The use case for the feature.
      placeholder: |
        ex: I want to be able to...
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A description of the feature.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: The acceptance criteria for the feature.
      placeholder: |
        ex: 
        - User can...
        - User cannot...
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      description: The browsers the feature should be compatible with.
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - IE11
      default: 0
  - type: checkboxes
    id: editions
    attributes:
      label: Editions
      description: The Salesforce editions the feature should be compatible with.
      options:
        - label: Enterprise
        - label: Essentials
        - label: Professional
  - type: checkboxes
    id: clouds
    attributes:
      label: Clouds
      description: The Salesforce clouds the feature should be compatible with.
      options:
        - label: Sales
        - label: Community
        - label: Service
        - label: FSC
        - label: Health
        - label: CPQ
  - type: checkboxes
    id: experiences
    attributes:
      label: Experiences
      description: The Salesforce experiences the feature should be compatible with.
      options:
        - label: Lightning
        - label: Classic
        - label: Mobile